config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :quizmasters

  resources :questions

  resources :quizzes

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/quizmaster.rb
class Quizmaster < ActiveRecord::Base
  belongs_to :user
  belongs_to :quiz
  has_many :quizzes
end

app/controllers/quizmasters_controller.rb
class QuizmastersController < ApplicationController
  before_action :set_quizmaster, only: [:show, :edit, :update, :destroy]

  # GET /quizmasters
  # GET /quizmasters.json
  def index
    @quizmasters = Quizmaster.all
  end

  # GET /quizmasters/1
  # GET /quizmasters/1.json
  def show
  end

  # GET /quizmasters/new
  def new
    @quizmaster = Quizmaster.new
  end

  # GET /quizmasters/1/edit
  def edit
  end

  # POST /quizmasters
  # POST /quizmasters.json
  def create
    @quizmaster = Quizmaster.new(quizmaster_params)

    respond_to do |format|
      if @quizmaster.save
        format.html { redirect_to @quizmaster, notice: 'Quizmaster was successfully created.' }
        format.json { render :show, status: :created, location: @quizmaster }
      else
        format.html { render :new }
        format.json { render json: @quizmaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizmasters/1
  # PATCH/PUT /quizmasters/1.json
  def update
    respond_to do |format|
      if @quizmaster.update(quizmaster_params)
        format.html { redirect_to @quizmaster, notice: 'Quizmaster was successfully updated.' }
        format.json { render :show, status: :ok, location: @quizmaster }
      else
        format.html { render :edit }
        format.json { render json: @quizmaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizmasters/1
  # DELETE /quizmasters/1.json
  def destroy
    @quizmaster.destroy
    respond_to do |format|
      format.html { redirect_to quizmasters_url, notice: 'Quizmaster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quizmaster
      @quizmaster = Quizmaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quizmaster_params
      params.require(:quizmaster).permit(:user_id, :quizid, :score, :quiz_id)
    end
end

app/helpers/quizmasters_helper.rb
module QuizmastersHelper
end

app/views/quizmasters/_form.html.erb
<%= form_for @quizmaster, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :quizid, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :quizid, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :score, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :score, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  quizmasters_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/quizmasters/edit.html.erb
<%- model_class = Quizmaster -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Quizmaster %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quizmasters/index.html.erb
<%- model_class = Quizmaster -%>
<div class="page-header">
  <h1><%=t '.title', :default => Quizmaster %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:quizid) %></th>
      <th><%= model_class.human_attribute_name(:score) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @quizmasters.each do |quizmaster| %>
      <tr>
        <td><%= quizmaster.id %></td>
        <td><%= quizmaster.quizid %></td>
        <td><%= quizmaster.score %></td>
        <td><%=l quizmaster.created_at, format: :long %></td>
        <td>
          <%= link_to quizmaster_path(quizmaster), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to quizmaster_path(quizmaster), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_quizmaster_path,
            :class => 'btn btn-primary' %>

app/views/quizmasters/new.html.erb
<%- model_class = Quizmaster -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Quizmaster %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quizmasters/show.html.erb
<%- model_class = Quizmaster -%>
<div class="page-header">
  <h1><%=t '.title', :default => Quizmaster %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:quizid) %></dt>
      <dd><pre class="prettyprint"><%= @quizmaster.quizid %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:score) %></dt>
      <dd><pre class="prettyprint"><%= @quizmaster.score %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              quizmasters_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_quizmaster_path(@quizmaster), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              quizmaster_path(@quizmaster),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>